name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  SECRETS_CONTEXT: ${{ toJson(secrets) }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - run: |
            format_env() { jq -r "to_entries[] | \"export \(.key)=\(.value)\""; }
            [[ "$SECRETS_CONTEXT" != "null" ]] && ENV_SECRETS="$(echo $SECRETS_CONTEXT | format_env)"
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only --build-secret "test=okay"